"""initial migrations

Revision ID: 6bfad1593364
Revises: e508e5988279
Create Date: 2021-09-30 11:26:56.246141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfad1593364'
down_revision = 'e508e5988279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'category')
    # ### end Alembic commands ###
